source("R/create-objects.R", local = TRUE)
source("R/convexity.R", local = TRUE)
source("R/curve.R", local = TRUE)
source("R/date-arithmetic.R", local = TRUE)
source("R/generics.R", local = TRUE)
source("R/graph.R", local = TRUE)
source("R/holiday_offset.R", local = TRUE)
source("R/instrument.R", local = TRUE)
source("R/instrument-list.R", local = TRUE)
source("R/interpolation.R", local = TRUE)
source("R/parameters.R", local = TRUE)
source("R/tests.R", local = TRUE)
.onAttach(RateHike, RateHike)
